### ISSUE TITLE
Adding binary files

### ISSUE THREAD

**Issue by achrys** [dasmoth/dalliance#137]
Currently, I face two issues with dalliance when trying to add bigbed files. 

1) I have an error when a URL parameter already exists in the link. I have managed to fix this issue with the following, and I would appreciate if the change is permanent. 

In utils.js

function saltURL(url) {

    if (url.indexOf('?') < 0) {
        return url + '?salt=' + b64_sha1('' + Date.now() + ',' + (++__dalliance_saltSeed));
    } else { 
        return url + '&salt=' + b64_sha1('' + Date.now() + ',' + (++__dalliance_saltSeed));
    }
}

2) When adding the following, 

http://www80.lamp.le.ac.uk/download?get=gencode.v20.annotation.bb

the file is processed successfully, but it is stuck with the connecting message. Additionally, I get "Uncaught RangeError: byte length of Int32Array should be a multiple of 4" error in the console.

**Comment by dasmoth** [comment]
1) As it happens, we've already made a somewhat-analogous change to handle URIs containing a '?' character, although the change is make [here](https://github.com/dasmoth/dalliance/blob/master/js/bin.js#L115) rather than in utils.  This change should have made it into the recent 0.13.0 release.

2) That server doesn't appear to support HTTP "Range" requests, which are required by Biodalliance so that it can fetch portions of the file based on the index.  You can test this straightforwardly with:

           curl -o test.bb -r 0-499 http://www80.lamp.le.ac.uk/download?get=gencode.v20.annotation.bb

(should retrieve 500 bytes, actually retrieves the whole file).

Secondarily, this server also doesn't support the HTTP OPTIONS command, which could cause problems for Biodalliance unless you never make cross-origin requests to this resource.

If possible, I'd suggest just using a "standard" web-server (Apache, nginx, etc.) pointed at a directory of files when serving up bigbeds.  If this isn't an option, you'll need to ensure that whatever you're using supports Range and OPTIONS.
