### ISSUE TITLE
second bigbed source fails when maxWorkers>0

### ISSUE THREAD

**Issue by ajo2995** [dasmoth/dalliance#180]
I have configured two bigbed sources. When I have maxWorkers:0 both sources are displayed properly, but otherwise only the first one is displayed. I'm having trouble debugging this, but the features for the second source end up having the type:'bigwig' instead of 'bigbed'. I tried to put a breakpoint in bigbed.js where it reads the magic numbers to get the type, but this function doesn't seem to be called by the worker threads (or the debugger can't track that).

**Comment by dasmoth** [comment]
Thanks very much for reporting this.  It turns out that there was a slightly old version of the worker code floating around, which I've now updated.

I've also run into a little issue in the trackhub-to-stylesheet converter, which had been substantially masking this issue.  Fixed in 0.13.7.

Let me know if you're still seeing problems at your end after these fixes.
